set_property SRC_FILE_INFO {cfile:D:/vivado/Project/ICache/UltraMIPS/ICache.srcs/constrs_1/new/soc_lite.xdc rfile:../../../ICache.srcs/constrs_1/new/soc_lite.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC19 [get_ports clk]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y3 [get_ports resetn]
