# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/NSCSCC/Project/ICache/ICache.srcs/sources_1/ip/tag_ram/tag_ram.xci
# IP: The module: 'tag_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/NSCSCC/Project/ICache/ICache.srcs/sources_1/ip/tag_ram/tag_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tag_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/NSCSCC/Project/ICache/ICache.srcs/sources_1/ip/tag_ram/tag_ram.xci
# IP: The module: 'tag_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/NSCSCC/Project/ICache/ICache.srcs/sources_1/ip/tag_ram/tag_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tag_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
