webtalk_init -webtalk_dir D:/vivado/Project/ICache/UltraMIPS/ICache.sim/sim_1/behav/xsim/xsim.dir/CacheAXI_Interface_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jul 14 17:36:55 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a3c462ca-bc77-48b4-9251-fa58af4ccf10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0589f301d5864ca9b22964510adc4723" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "52" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6328_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1937207143 -regid "" -xml D:/vivado/Project/ICache/UltraMIPS/ICache.sim/sim_1/behav/xsim/xsim.dir/CacheAXI_Interface_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/vivado/Project/ICache/UltraMIPS/ICache.sim/sim_1/behav/xsim/xsim.dir/CacheAXI_Interface_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/vivado/Project/ICache/UltraMIPS/ICache.sim/sim_1/behav/xsim/xsim.dir/CacheAXI_Interface_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
