# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/tag_ram/tag_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tag_ram || ORIG_REF_NAME==tag_ram} -quiet] -quiet

# IP: ip/bank_ram/bank_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bank_ram || ORIG_REF_NAME==bank_ram} -quiet] -quiet
